version: '3'

services:
  webserver:
    image: php:8.0.1-fpm
    volumes:
      - ./web:/var/www/html
    networks:
      - web
  nginx:
    image: nginx
    ports:
      - "8090:80"
    volumes:
      - ./web:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web

networks:
  web:
